server:
  port: 8080
  servlet:
    session:
      timeout: 60
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/icesdemo?characterEncoding=utf-8&&useSSL=true&serverTimezone=GMT"
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    suffix: .html
    check-template-location: true
    encoding: utf-8
    mode: HTML
    servlet:
      content-type: text/html
mybatis:
  type-aliases-package: com.example.demo.pojo
  mapper-locations: classpath:mapper/*.xml